# Generated by Django 5.1.3 on 2024-12-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_policy_date_alter_labour_hour_bcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
