# Generated by Django 5.1.3 on 2024-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_cart_name_product_name_request_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
