# Generated by Django 3.2.14 on 2024-12-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_complaint_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requesttable',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
