# Generated by Django 3.2.14 on 2024-12-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
