# Generated by Django 5.1.3 on 2024-12-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttable',
            name='name',
        ),
    ]
