# Generated by Django 5.1.3 on 2024-12-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_alter_requesttable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='businessName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='businessType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmLocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
