# Generated by Django 3.2.14 on 2024-12-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_business_businessname_business_businesstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
