# Generated by Django 3.2.14 on 2024-12-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_usertable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='status',
            field=models.CharField(blank=True, default='rejected', max_length=100, null=True),
        ),
    ]
