# Generated by Django 5.1.3 on 2025-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_alter_business_address_alter_business_businessname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='mob_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
