# Generated by Django 5.1.3 on 2025-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_alter_farmer_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
